// 35 minutes
:revealjs_totalTime: 2100

= Why Event Sourcing Is Hard?

Mateusz Kubuszok

== About me

[%step]
* breaking things in Scala for 7+ years
* breaking things for money for 10 years
* breaking things for fun for 18(?) years
* a little bit of open source
* blog at https://kubuszok.com[Kubuszok.com]
* niche https://leanpub.com/jvm-scala-book[Things you need to know about JVM (that matter in Scala)] ebook

[NOTE.speaker]
--
Every presentation should staart with some excuse, why you even are here
--

== Agenda

[%step]
* What is Event Sourcing?
* Pitfalls of processing events
* Pitfalls of creating events
* Other pittfals
* Summary

[NOTE.speaker]
--
Disclaimer: people who worked with event sourcing most likely experiences all if these so they can take everything in this presentation as granted.
--

== What is Event Sourcing?

[NOTE.speaker]
--
Instead of starting with a dry definition, let's go on a small journey.
--

=== !

[source, scala]
--
case class User(id: String, name: String)
--

[source, scala]
--
// called directly by UI
def changeUsername(userID:  String, newName: String): Unit =
  val user = getUser(userID)
  val updatedUser = user.copy(name = newName)
  saveUser(user)
--

[source, scala]
--
// fetch from DB
def getUser(userID: String): User

// saves to DB
def saveUser(user: User): Unit
--

[NOTE.speaker]
--
Sorry for not purely functional code, but I didn't want to spend first half pf presentation explaining monads.

Here we have a code which couples action, which how and when it is executed. Let's decouple things a bit.
--

=== !

[source, scala]
--
trait UserActionListener:
  def changeUsername(userID: String, newName: String)
--

[source, scala]
--
// added to UI
val userActionListeners: List[UserActionListener]

// still in UI
def changeUsername(userID: String, newName: String): Unit =
  userActionListeners.foreach { listener =>
    listener.changeUsername(userID, newName)
  }
--

[NOTE.speaker]
--
Here we have a solution popular in many GUI frameworks.

We decoupled the UI from the action that it performs.

But every component still needs its own collection of listeners.

And everything is still blocking and synchronous.
--

=== !

[source, scala]
--
enum UserAction:
  case ChangeUsername(userID: String, newName: String)

trait UserActionEventBus:
  def publish(action: UserAction): Unit
  def subscribe(f: UserAction => Unit): Unit
--

[source, scala]
--
// in UI
def changeUsername(userID: String, newName: String): Unit =
  bus.publish(UserAction.ChangeUserName(userID, newName))
--

[source, scala]
--
// elsewere
bus.subscribe {
  case UserAction.ChangeUsername(userID, newName) => ...
  case _ => ()
}
--

[NOTE.speaker]
--
Now, everyone can write to the event bus, and also anyone can listen.

That gives a lot of flexibity. But, why should we limit ourselved to just local application? At this point we can send the events over wire and respond to them anytime!

But this still defines what needs to happen, not what happened, it is not deterministic in case someone doesn't respond to command in time!
--

[transition="slide-in fade-out"]
=== !

[source, scala]
--
enum UserEvent:
  def userID: String

  case UsernameChanged(userID: String, newName: String)
--

[source, scala]
--
// journal of UserEvents
// instead of List it might be Stream, Iterator or Producer
val userEvents: List[UserEvent]
--

[source, scala]
--
val userID: String // specific User's ID

userEvents.foldLeft(User(id = userID, name = "")) {
  (user, event) =>
    event match
      case UserEvent.UsernameChanged(id, name) =>
        if (id == userID) user.copy(name = name)
        else user
} // returns User with all events applied
--

[NOTE.speaker]
--
Here, we decided to represent what happened, rather than what is requested to happen.

This allows us to deterministically compute state. It is decoupled with when it happened and where it happened.

We might change our about what to start with and how to use each event, and we can still compute the state because we rememver everything.

But this is the toy example because we got rid of side effects. It only appears in e.g. React or similar.

But remember this foldLeft intuition! In two steps it will stop looking like this while still preserving this intution.
--

[transition="fade-in slide-out"]
=== !

[source, scala]
--
enum UserEvent:
  def userID: String

  case UsernameChanged(userID: String, newName: String)
--

[source, scala]
--
// journal of UserEvents
// this has to be streamed from the outer world
val userEvents: List[UserEvent]
--

[source, scala]
--
val userID: String // specific User's ID

userEvents.foldLeft(User(id = userID, name = "")) {
  (user, event) =>
    event match
      case UserEvent.UsernameChanged(id, name) =>
        if (id == userID) user.copy(name = name)
        else user // result should be stored somewhere
}
--

[transition="slide-in fade-out"]
=== !

[source, scala]
--
val userID: String // specific User's ID
--

[source, scala]
--
def fetchUser(): Option[User] // current projection state
val lastOffset: String // last processed event
def userEvents(offset: String): Stream[(UserEvent, Offset)]
--

[source, scala]
--
userEvents(lastOffset).foldLeft(
  fetchUser().getOrElse(User(id = userID, name = ""))
) { (user, eventWithOffset) =>
  eventWithOffset match
    case (UserEvent.UsernameChanged(id, name), offset) =>
      val newUser =
        if (id == ourUserID) user.copy(name = name)
        else user
      saveUser(newUser) // persists projection's state
      saveOffset(offset) // persist projection's offset
      newUser
}
--

[NOTE.speaker]
--
This still resembles the ``foldLeft code``, to ease in how the code will usually look like.
--

[transition="fade-in slide-out"]
=== !

[source, scala]
--
val userID: String // we should compute all entities!
--

[source, scala]
--
def fetchUser(): Option[User] // should handle all users!
val lastOffset: String // offset absent before the 1st run!
def userEvents(offset: String): Stream[(UserEvent, Offset)]
--

[source, scala]
--
userEvents(lastOffset).foldLeft(
  fetchUser().getOrElse(User(id = userID, name = ""))
) { (user, eventWithOffset) =>
  eventWithOffset match
    case (UserEvent.UsernameChanged(id, name), offset) =>
      val newUser =
        if (id == ourUserID) user.copy(name = name)
        else user
      saveUser(newUser) // persists projection's state
      saveOffset(offset) // persist projection's offset
      newUser // we don't need to return a value here!
} // and neither here!
--

=== !

[source, scala]
--
// persisted for each projection
def fetchLastOffset:() Option[String]
// returns User's projection's state by their ID
def fetchUser(userID: String): Option[User]
--

[source, scala]
--
eventsFrom(fetchLastOffset()).foreach { eventWithOffset =>
  eventWithOffset match
    case (UserEvent.UsernameChanged(id, name), offset) =>
      val user = fetchUser(id) // current projection state
      val newUser = user.copy(name)
      saveUser(newUser) // persists projection's state
      saveOffset(offset) // persist projection's offset
} // returns Unit (void)
--

[NOTE.speaker]
--
This is the typical projection that you'll find on production.
--

== Pitfalls of processing events

=== Commiting offset upfront


[transition="slide-in fade-out"]
=== !

[source, scala]
--
//
eventsFrom(fetchLastOffset()).foreach {
  case (UserEvent.UsernameChanged(id, name), offset) =>
    val user = fetchUser(id)
    val newUser = user.copy(name)
    saveUser(newUser)
    saveOffset(offset)
}
--

[NOTE.speaker]
--
I inlined pattern matching for convenience.

This isn't what some implementations will give you.
--

[transition="fade-in slide-out"]
=== !

[source, scala]
--
// what if this... \/
eventsFrom(fetchLastOffset()).foreach {
  case (UserEvent.UsernameChanged(id, name), offset) =>
    val user = fetchUser(id)
    val newUser = user.copy(name)
    saveUser(newUser)
    saveOffset(offset) // <- ...and this were done for you?
}
--

[transition="slide-in fade-out"]
=== !

[source, scala]
--
// 1. fetches the last offset of the projection
// 2. starts streaming events since last offset
// 3. commits offset before returning event
def newEvents(): Stream[UserEvent]
--

[source, scala]
--
newEvents().foreach {
  // no need to pass offset here!
  case UserEvent.UsernameChanged(id, name)) =>
    val user = fetchUser(id)
    val newUser = user.copy(name)
    saveUser(newUser) // nor save it here!
}
--

[NOTE.speaker]
--
This is what many Akka Streams integrations (Alpakka) do by default.
--

[transition="fade"]
=== !

[source, scala]
--
// 1. fetches the last offset of the projection
// 2. starts streaming events since last offset
// 3. commits offset before returning event
def newEvents(): Stream[UserEvent]
--

[source, scala]
--
newEvents().foreach {
  case UserEvent.UsernameChanged(id, name)) =>
    // let's say process the crashed when we were here
    val user = fetchUser(id)
    val newUser = user.copy(name)
    saveUser(newUser)
}
--

[NOTE.speaker]
--
Event ends up not being projected!
--

[transition="fade-in slide-out"]
=== !

[source, scala]
--
// 1. fetches the last offset of the projection
// 2. starts streaming events since last offset
// 3. DOES NOT commits offset before returning event
def newEvents(): Stream[(UserEvent, Offset)]
--

[source, scala]
--
newEvents().map {
  case (UserEvent.UsernameChanged(id, name)), offset) =>
    val user = fetchUser(id)
    val newUser = user.copy(name)
    saveUser(newUser)
    offset
}.foreach(offset => saveOffset(offset))
--

[NOTE.speaker]
--
Saving offset yourself prevents the situation when event get lost.

But what if app crash and we did something that shouldn't be repeated?
--

=== Lack of idempotency

[transition="slide-in fade-out"]
=== !

[source, scala]
--
newEvents().map {
  case (UserEvent.UsernameChanged(id, name)), offset) =>
    val user = fetchUser(id)
    val newUser = user.copy(name)
    saveUser(newUser)
    sendUserNotification(newUser, "Name updated")
    offset
}.foreach(offset => saveOffset(offset))
--

[NOTE.speaker]
--
``sendUserNotification`` talks to external world.
--

[transition="fade"]
=== !

[source, scala]
--
newEvents().map {
  case (UserEvent.UsernameChanged(id, name)), offset) =>
    val user = fetchUser(id)
    val newUser = user.copy(name)
    saveUser(newUser)
    sendUserNotification(newUser, "Name updated")
    offset // app killed while here
}.foreach(offset => saveOffset(offset))
--

[NOTE.speaker]
--
If app was killed before we commited offset, then there will be another attempt to project the event.
--

[transition="fade-in slide-out"]
=== !

[source, scala]
--
newEvents().map { // add event ID  \/  should be unique
  case (UserEvent.UsernameChanged(eid, id, name)),offset) =>
    val user = fetchUser(id)
    val newUser = user.copy(name)
    saveUser(newUser, eid)
    sendUserNotification(newUser, "Name updated", eid)
    offset // app killed while here
}.foreach(offset => saveOffset(offset))
--

[NOTE.speaker]
--
Now, we can create a queue of notifications, and verify that some action was already requested.
--

=== Shared global state

=== !

[source, scala]
--
val events = List(
  ...
  UserEvent.UsernameChanged(..., id="user-1", name="foo"),
  ...
  UserEvent.UsernameChanged(..., id="user-2", name="foo"),
  ...
)
--

[%step]
A few months later, let's introduce requrement that ``name`` should globally unique.

[NOTE.speaker]
--
We allowed users to have overlapping values, but then we changed it. What to do with them?
--

=== Projecting events in parallel within the same projection

=== !

[source, scala]
--
...
// user quickly changed its name twice
UserEvent.UsernameChanged(..., id="user-1", name="foo"),
UserEvent.UsernameChanged(..., id="user-1", name="bar"),
...
--

[%step]
Node 1:
[%step]
[source, scala]
--
...
UserEvent.UsernameChanged(..., id="user-1", name="foo"),
...
--

[%step]
Node 2:
[%step]
[source, scala]
--
...
UserEvent.UsernameChanged(..., id="user-1", name="bar"),
...
--

[NOTE.speaker]
--
Race condition: whichever event handler will be later will set the value.
--

=== !

[source, scala]
--
// user quickly changed its name twice
UserEvent.UsernameChanged(..., id="user-1", name="foo"),
UserEvent.UsernameChanged(..., id="user-1", name="bar"),
// then another user takes its old name
UserEvent.UsernameChanged(..., id="user-2", name="foo"),
--

[%step]
Node 1:
[%step]
[source, scala]
--
...
UserEvent.UsernameChanged(..., id="user-1", name="foo"),
UserEvent.UsernameChanged(..., id="user-2", name="foo"),
...
--

[%step]
Node 2:
[%step]
[source, scala]
--
...
UserEvent.UsernameChanged(..., id="user-1", name="bar"),
...
--

[NOTE.speaker]
--
Node 1 might try o use a name that hasn't been freed yet.
--

== Pitfalls of creating events

=== Lack of idempotency

=== !

[source, scala]
--
// send to bounded context when we want to change something
enum UserCommand:
  case ChangeUsername(id: String, name: String)

// returned when the command failed
enum UserError:
  case UsernameTaken
  case UserNotExist
--

[%step]
[source, scala]
--
val handleUserCommand:
    UserCommand => Either[UserCommand, UserError] = {
  case UserCommand.ChangeUsername(id, name) =>
    if userExists(id) then Right(
      UserEvent.UsernameChanged(randomEventId(), id, name)
    )
    else Left(UserError.UserNotExist)
}
// Right values (events) are saved to events journal
// Left values (errors) can be returned to caller
--

[%step]
[source, scala]
--
UserCommand.ChangeUsername("1", "foo")//client did 3 retries
--

[NOTE.speaker]
--
Let's say your browser had connectivity issues and app send the same command twice or trice.

You have now 3 events, even though you wanted it once.

Messages on social media is a good example od this. Adding to basket. Microservies creating commands in projections.
--

=== Relying on the state from projection

=== !

[source, scala]
--
val handleUserCommand:
    UserCommand => Either[UserCommand, UserError] = {
  case UserCommand.ChangeUsername(cmdId, id, name) =>
    if !userExists(id) then Left(UserError.UserNotExist)
    //           \/ asks the DB updated by this projection
    else if !usernameTaken(id, name) then Left(
      UserError.UsernameTaken
    )
    else Right(
      UserEvent.UsernameChanged(eventId(cmdId), id, name)
    )
}
--

[%step]
[source, scala]
--
// 2 users try to reserve the same username at the same time
UserCommand.ChangeUsername(id="1", name="foo")
UserCommand.ChangeUsername(id="2", name="foo")
--

[NOTE.speaker]
--
Two users sending update at once could create a race condition followed by broken state.
--

=== Lack of atomicity

=== !

[source, scala]
--
val handleUserCommand:
    UserCommand => Either[UserCommand, UserError] = {
  case UserCommand.ChangeUsername(cmdId, id, name) =>
    if !userExists(id) then Left(UserError.UserNotExist)
    else if !reserveUsernameForUser(id, name) then Left(
      UserError.UsernameTaken
    )
    // here the server crashes :)
    else Right(
      UserEvent.UsernameChanged(eventId(cmdId), id, name)
    )
}
--

[NOTE.speaker]
--
Command handler is the place where we are making sure that make sure that event can be created.

If this logic requires side effects if might be dangerous if we don't guarantee atomicity.
--

== Other difficulties that might (will) happen

=== !

[%step]
* your events will evolve over time and their format will change
* you will talk to external APIs that you cannot control, which will make idempotency difficult or impossible
* you will have bugs resulting in events that shouldn't have been created
* and many more

== Summary

=== !

Ask yourself what will happen when:

[%step]
* your process crashes/gets killed
* someone sends the same event/command twice
* you need to rerun projection from some point in past (maybe even from the start)
* the format of your events needs to change

[%step]
Would you arrive at the same state in the end?

[NOTE.speaker]
--
Is the final state the deterministic outcome of our history?
--

=== !

Also ask yourself:

[%step]
* why you used Event Sourcing in the first place
* is the way you use it helping achieving you your goal
* what is the worst outcome of doing ES "wrong"

[NOTE.speaker]
--
If the worst that can happen is not that bad, then there is hardly any reason to be "dogmatic".
--

== Questions?

== Thank you!

